services:
  php74:
    build:
      context: .
      dockerfile: Dockerfile.74
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./log:/var/log/apache2

  db:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 8081:80